name: pull_request_to_dev

on:
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: 3
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello, world!"

