services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 1234
    healthcheck:
      test: rabbitmq-diagnostics -q alarms || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  waiting-for-the-services-to-be-ready:
    image: hello-world
    depends_on:
      rabbitmq:
        condition: service_healthy
