name: 'release-plan-message'
description: 'Release plan message generated for changeset status output as input to this action'
inputs:
  json-string:
    description: 'JSON string'
    required: true
outputs:
  release-plan-message:
    description: 'Release plan message'
runs:
  using: 'node16'
  main: 'dist/index.js'
