name: check_dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1,3' # 5:30am on Monday and Wednesday (UTC)
    - cron: '30 5 * * 2,4' # 5:30am on Tuesday and Thursday (UTC)
env:
  FORCE_COLOR: 3
defaults:
  run:
    shell: bash

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
#      - name: Not on Monday or Wednesday
#        if: github.event.schedule != '30 5 * * 1,3'
#        run: echo "This step will be skipped on Monday and Wednesday"
#      - name: Every time
#        run: echo "This step will always run"
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Check dependencies
        id: check_dependencies
        run: |
          output=$(npx npm-check-updates --target minor --jsonUpgraded)
          num_properties=$(echo "$output" | jq 'length')
          if [ "$num_properties" -gt 0 ]; then
            echo "The JSON contains properties."
          else
            echo "The JSON is not empty but has no properties."
          fi
          echo "num_properties=$num_properties" >> $GITHUB_OUTPUT
      - name: Update dependencies
        if : ${{ steps.check_dependencies.outputs.num_properties > 0 }}
        run: |
          npx npm-check-updates --target minor -u
          pnpm install --no-frozen-lockfile && pnpm dedupe
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'build(deps): Upgrade NPM packages (automated)'
          branch: 'upgrade-npm-packages'
          commit-message: 'build(deps): upgrade NPM packages (automated)'

