name: Release
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  FORCE_COLOR: 3

jobs:
  changelog:
    permissions:
      contents: write
      pull-requests: write
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        with:
#          repository: ${{ github.event.pull_request.head.repo.full_name }}
#          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Note: pnpm install after versioning is necessary to refresh lockfile, TODO: FROZEN???
          version: pnpm exec changeset version
          publish: pnpm exec changeset publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Needs access to publish to npm
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
# que no quede aca, tambien que se genere notificaciones al slack -> develop, al luis a alexis, etc.-...
      - name: Generate Notification
        id: notification
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "Published Packages: ${{ steps.changesets.outputs.publishedPackages }}"

